config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "tasks", to: "tasks#index"
  # get "tasks/new", to: "tasks#new"
  # get "tasks/:id", to: "tasks#show", as: :task
  # get "tasks/:id/edit", to: "tasks#edit"

  # post "tasks", to: "tasks#create"
  # patch "tasks/:id", to: "tasks#update"
  # delete "tasks/:id", to: "tasks#destroy"
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.erb
<%= form_for @task do |f| %>
  <div class="form-group">
    <%= f.label :title %>:
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>:
    <%= f.text_area :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_for @task do |f| %>
  <div class="form-group">
    <%= f.label :title %>:
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>:
    <%= f.text_area :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :completed, "Completed", {class: "checkbox inline"} %>
    <%= f.check_box :completed %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<hr>

<i class="fa fa-undo" aria-hidden="true">
  <%= link_to "Back to the list", tasks_path, { :class => "link" } %>
</i>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul class="tasks">
  <% @tasks.each do |task| %>
    <li>
      <%= check_box_tag task.title, task.title, ( task.completed ) %>
      <%= link_to task.title, task_path(task.id) %>
      <%= link_to '<i class="fa fa-trash"></i>'.html_safe, task_path(task.id),
        method: :delete,
        data: { confirm: "Delete #{task.title}?" } %>
    </li>

  <% end %>
</ul>
<hr>

<i class="fa fa-plus">
  <%= link_to "Add new task", new_task_path %>
</i>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form', task: @task %>

<hr>

<i class="fa fa-undo" aria-hidden="true">
  <%= link_to "Back to the list", tasks_path, { :class => "link" } %>
</i>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<div class="task">
  <a class="btn btn-outline-secondary edit" href=<%= "#{@task.id}/edit" %>>
    <i class="fa fa-pencil"></i><strong>Edit task</strong>
  </a>


  <div class="details">
    <%= @task.details %>
  </div>

  <div class="info">
    <% if @task.completed %>
      <%= check_box_tag @task.title, @task.title, ( @task.completed ) %>
      <span>The task is completed</span>
    <% else %>
      <%= check_box_tag @task.title, @task.title %>
      <span>The task is not completed yet</span>
    <% end %>
  </div>
</div>

<hr>

<i class="fa fa-undo" aria-hidden="true">
  <%= link_to "Back to the list", tasks_path, { :class => "link" } %>
</i>